window.JMEDIA_PROJECTS = [
  {
    slug: "policyfundpedia",
    title: "Policyfundpedia",
    type: "Information Hub",
    period: "5D",
    core: "SEO Structure",
    preview: "assets/portfolio/05_policyfundpedia.png",
  },
  {
    slug: "reportools",
    title: "Reportools",
    type: "Utility",
    period: "3D",
    core: "Input / Result",
    preview: "assets/portfolio/10_reportools.png",
  },
  {
    slug: "tripmarking",
    title: "Tripmarking",
    type: "Local Map",
    period: "7D",
    core: "Mobile Map",
    preview: "assets/portfolio/08_tripmarking.png",
  },
  {
    slug: "goatool",
    title: "Goatool",
    type: "Tool Site",
    period: "3D",
    core: "One-click Flow",
    preview: "assets/portfolio/09_goatool.png",
  },
  {
    slug: "ahachive",
    title: "Ahachive",
    type: "Archive",
    period: "3D",
    core: "Curation",
    preview: "assets/portfolio/01_ahachive.png",
  },
  {
    slug: "occult-worldcup",
    title: "Occult Worldcup",
    type: "Engagement",
    period: "4D",
    core: "Play Loop",
    preview: "assets/portfolio/03_occultworldcup.png",
  },
  {
    slug: "sumimap",
    title: "Sumimap",
    type: "Local Data",
    period: "7D",
    core: "Report UX",
    preview: "assets/portfolio/06_sumimap.png",
  },
  {
    slug: "scamreader",
    title: "Scamreader",
    type: "Guide",
    period: "3D",
    core: "Safety Copy",
    preview: "assets/portfolio/07_scamreader.png",
  },
];
